//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FineArtAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Posting
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Posting()
        {
            this.Exhibitions = new HashSet<Exhibition>();
        }
    
        public int PostingId { get; set; }
        public double Mark { get; set; }
        public string Quote { get; set; }
        public System.DateTime LastEdit { get; set; }
        public string ImagePath { get; set; }
        public int UserId { get; set; }
        public int CompetitionId { get; set; }
        public bool isActive { get; set; }
    
        public virtual Competition Competition { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Exhibition> Exhibitions { get; set; }
    }
}
